name: Account Management Authorization Form
description: Submit an account related authorization
labels: ['icam']
body:
  - type: dropdown
    id: account-authorized
    attributes:
      label: Account authorization
      description: Select the action from the drop-down
      options:
        - Approved
        - Not approved
      multiple: false
    validations:
      required: true
  - type: dropdown
    id: account-created
    attributes:
      label: Account creation
      description: Select the action from the drop-down
      options:
        - Created
        - Not created
      multiple: false
    validations:
      required: true
  - type: dropdown
    id: account-created-by
    attributes:
      label: Account creation by
      description: Select the action from the drop-down
      options:
        - Admin
        - Account manager
      multiple: false
    validations:
      required: true
  - type: dropdown
    id: account-approved-by
    attributes:
      label: Account approval by
      description: Select the action from the drop-down
      options:
        - Michaela
        - Dmitry
      multiple: false
    validations:
      required: true
  - type: textarea
    id: comments
    attributes:
      label: Comments
      placeholder: (optional) Type in here any additional information related to this authorization.
    validations:
      required: false
