name: Account Management Request Form
description: Submit an account related request
labels: ['icam']
body:
  # - type: checkboxes
  #   attributes:
  #     label: Is there an existing request for this?
  #     description: Please search to see if a request already exists for this user with similar action requested.
  #     options:
  #       - label: I have searched the existing issues
  #         required: true
  - type: input
    id: first-name
    attributes:
      label: First Name
      placeholder: Type here user's first name as it appears in his/her ID.
    validations:
      required: true
  - type: input
    id: last-name
    attributes:
      label: Last Name
      placeholder: Type here user's last name as it appears in his/her ID.
    validations:
      required: true
  - type: dropdown
    id: account-requested-by
    attributes:
      label: Who requested the account
      description: Select the action from the drop-down
      options:
        - System Owner
        - Admin
        - Security
        - User
        - Account Manager
      multiple: false
    validations:
      required: true
  - type: dropdown
    id: account-type
    attributes:
      label: What account type is requested
      description: Select the action from the drop-down
      options:
        - Admin
        - User
        - Assessor
        - ISSO
      multiple: false
    validations:
      required: true
  - type: dropdown
    id: account-managers
    attributes:
      label: Account approvers
      description: Select the action from the drop-down
      options:
        - Michaela
        - Dmitry
      multiple: false
    validations:
      required: true
  - type: dropdown
    id: account-group-or-role
    attributes:
      label: What account group or role
      description: Select the action from the drop-down
      options:
        - Admin
        - User
        - Security
      multiple: false
    validations:
      required: true
  - type: dropdown
    id: account-privileges
    attributes:
      label: What account privilege is requested
      description: Select the action from the drop-down
      options:
        - Read
        - Read/Write
      multiple: false
    validations:
      required: true
  - type: dropdown
    id: account-modification
    attributes:
      label: What account modification is requested
      description: Select the action from the drop-down
      options:
        - Create
        - Disable
        - Enable
        - Modify
        - Remove
      multiple: true
    validations:
      required: true
  # - type: textarea
  #   id: bug-conditions
  #   attributes:
  #     label: When does this occur
  #     description: Describe the conditions under which the bug is occuring
  #   validations:
  #     required: true
  - type: textarea
    id: comments
    attributes:
      label: Comments
      placeholder: (optional) Type in here any additional information related to this request.
    validations:
      required: false

